### ISSUE TITLE
Multi-slaves (multi-JVMs) support on the same node

### ISSUE THREAD

**Issue by pfxuan** [PasaLab/dfs-perf#2]
A single JVM instance only can achieve about 8 GB/s write throughput, which is far away from 100+ GB/s memory bandwidth supplied by modern memory system. To fully saturate the capacity of in-memory file system, DFS-PERF should have such ability to deploy multi-slaves on a single physical node. The followings is the perfomrance details:  
https://groups.google.com/forum/#!starred/alluxio-users/hwlfwu0B4Tg

**Comment by swatDong** [comment]
You can modify the `conf/slaves` to launch multi-slaves on a single node, e.g., the following means 2 slaves on node1 and 4 slaves on node2.

    node1
    node1
    node2
    node2
    node2
    node2

**Comment by pfxuan** [comment]
@swatDong, this works perfectly. Thanks for your quick response!
